GET https://gentle-ridge-77245.herokuapp.com/api/persons/4

###
GET https://gentle-ridge-77245.herokuapp.com/api/persons

###

DELETE https://gentle-ridge-77245.herokuapp.com/api/persons/8481

###
POST https://gentle-ridge-77245.herokuapp.com/api/persons
Content-Type: application/json

{
     "name": "Kirikou",
    "number": "345678-56778"
}

